spring:
  application:
    name: one-redis
  dubbo:
    registry: zookeeper://one-zk:2181
    protocol:
      name: dubbo
      port: 20886
    provider:
      timeout: 20000
server:
  port: 8180
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: WARN
    web:  WARN
    com:
      example:
        one:
          redis:
            service:
              term: INFO
  file: logs/spring-boot-logging.log
