FROM nginx
MAINTAINER  colorlightwzg<jerry.wong@lednets.com>
LABEL "author"="wzg"  "description"="nginx_ccloud"

EXPOSE 80    
EXPOSE 443

VOLUME ["/etc/letsencrypt","/var/lib/letsencrypt","/var/www/html","/usr/share/nginx/html/backup/wp-content/uploads/"]